# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoint',
            old_name='starttime',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='appoint',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='appoint',
            old_name='xid',
            new_name='x_id',
        ),
        migrations.RenameField(
            model_name='appoint',
            old_name='xtype',
            new_name='x_type',
        ),
    ]
