# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20170521_1102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appoint',
            new_name='appoint_acm',
        ),
    ]
