# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20170521_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint_acm',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='用户名称'),
            preserve_default=False,
        ),
    ]
