# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_auto_20170521_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint_acm',
            name='user',
        ),
    ]
