# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appoint_acm_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint_lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('people', models.CharField(max_length=10, verbose_name='预约人数')),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Lecture', verbose_name='讲座')),
            ],
        ),
        migrations.CreateModel(
            name='appoint_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('people', models.CharField(max_length=10, verbose_name='预约人数')),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Station', verbose_name='讲座')),
            ],
        ),
    ]
